// auth
export const LOGIN_ACCOUNT = 'LOGIN_ACCOUNT';
export const RESET_LOGIN_ACCOUNT = 'RESET_LOGIN_ACCOUNT';
export const LOGIN_SOCIAL_ACCOUNT = 'LOGIN_SOCIAL_ACCOUNT';
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS';
export const LOGIN_ACCOUNT_ERROR = 'LOGIN_ACCOUNT_ERROR';

export const GET_TODO_LIST = 'GET_TODO_LIST';
export const GET_TODO_LIST_SUCCESS = 'GET_TODO_LIST_SUCCESS';
export const RESET_GET_TODO_LIST_LIST = 'RESET_GET_TODO_LIST_LIST';
